import pandas as pd
import os
a = "./data/b3/"


def filter(reg, **kwargs):
    result = 1
    if 'stocks' in kwargs:
        result = result*(reg[12:24].strip() in kwargs['stocks'])
    if 'type_of_market' in kwargs:
        result = result*(reg[24:27].strip() in kwargs['type_of_market'])
    return result
        


def bovespa_file_process(begin_date, end_date, folder='./data/b3', filter = filter, **kwargs):
    '''
        Process B3 file and returns a Pandas DataFrame with daily trading information for selected stocks between dates.
        Parameters:
            folder (str): path to folder containing B3 files
            stocks (iterable of str): list of stocks symbols(str) to fetch
            type_of_market (iterable of str): list of type of markets to fetch (010 spot market, 070 call options, 080 put options, 017 auction, 020 fraction, 030 forward market)  
            begin_date (str): date to start collecting (YYYY-MM-DD) 
            end_date (str): date to end collecting (YYYY-MM-DD) 
    '''
    info = {'date': [], 'cod_neg': [], 'cod_bdi': [], 'tpmerc': [], 'premed': [], 'preabe': [], 'premax': [], 'premin': [], 'preult': [], 'preofc': [], 'preofv': [], 'totneg': [], 'fatcot': []}

    for file_path in os.listdir(folder):
        file = open(os.path.join(folder, file_path))
        for reg in file:
            if reg[:2] == '00':
                print('Processing File ' + reg[2:15] + ' generated by ' + reg[15:23] + 'at ' + reg[23:27] + '-' + reg[27:29]+ '-' + reg[29:31])

            if reg[:2] == '01':
                if filter(reg, **kwargs):
                    if pd.to_datetime(reg[2:10], infer_datetime_format=True) >= pd.to_datetime(begin_date, infer_datetime_format=True) and pd.to_datetime(reg[2:10], infer_datetime_format=True) <= pd.to_datetime(end_date, infer_datetime_format=True):
                        info[ 'date'].append(pd.to_datetime(reg[2:10], infer_datetime_format=True))
                        info[ 'cod_bdi'].append(reg[10:12].strip())
                        info[ 'cod_neg'].append(reg[12:24].strip())
                        info[ 'tpmerc'].append(reg[24:27].strip())
                        info[ 'preabe'].append(float(reg[56:69])/100)
                        info[ 'premax'].append(float(reg[69:82])/100)
                        info[ 'premin'].append(float(reg[82:95])/100)
                        info[ 'premed'].append(float(reg[95:108])/100)
                        info[ 'preult'].append(float(reg[108:121])/100)
                        info[ 'preofc'].append(float(reg[121:134])/100)
                        info[ 'preofv'].append(float(reg[134:147])/100)
                        info[ 'totneg'].append(float(reg[147:152]))
                        info[ 'fatcot'].append(int(reg[210:217]))
        file.close()
        print('...file done')
    print('PROCESSING DONE')
    return pd.DataFrame(info)
